[project]
name = "boston-marathon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.2.3",
    "pdfplumber>=0.11.5",
    "pypdf>=5.3.0",
    "ruff>=0.9.6",
    "tabula-py>=2.10.0",
]
